# Generated by Django 5.2.17 on 2026-09-24 09:11

import common.utils.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepStudy',
            fields=[
                ('id', models.UUIDField(default=common.utils.uuid.get_uuid7, editable=False, primary_key=True, serialize=False)),
                ('study_date', models.DateField(help_text='Date recording began')),
                ('study_type', models.CharField(choices=[('cassette_home', 'Sleep-Cassette (Home Study)'), ('telemetry_hospital', 'Sleep-Telemetry (Hospital Study)'), ('full_psg', 'Full In-Lab Polysomnography')], default='full_psg', max_length=30)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded (Pending)'), ('extracting', 'Extracting Archive'), ('staging', 'Predicting 30s Sleep Stages'), ('computing_metrics', 'Extracting SQI & Metrics'), ('generating_report', 'Generating AI Clinical Report'), ('completed', 'Completed'), ('failed', 'Processing Failed')], db_index=True, default='uploaded', max_length=30)),
                ('raw_archive', models.FileField(blank=True, null=True, upload_to='studies/raw_zips/%Y/%m/')),
                ('extracted_path', models.CharField(blank=True, default='', help_text='Local filesystem path where files are extracted', max_length=512)),
                ('total_epochs', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Recording technical parameters, detected channels, lights-off window')),
                ('error_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='patients.patient')),
                ('physician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'studies_sleepstudy',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StudyFile',
            fields=[
                ('id', models.UUIDField(default=common.utils.uuid.get_uuid7, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('relative_path', models.CharField(help_text='Path relative to the extracted study directory', max_length=512)),
                ('file_type', models.CharField(choices=[('epoch_report', '30-Second Epoch Report'), ('raw_edf', 'Raw Polysomnography (.edf / .epf)'), ('annotation_edf', 'Hypnogram / Annotation (.edf)'), ('metadata_excel', 'Demographics / Protocol (.xls / .xlsx)'), ('numpy_array', 'Preprocessed Epoch Array (.npz)'), ('other', 'Other File')], db_index=True, default='other', max_length=30)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_hash_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('epoch_index', models.PositiveIntegerField(blank=True, db_index=True, help_text='0-indexed 30-second epoch number if file represents a single epoch', null=True)),
                ('preview_data', models.JSONField(blank=True, default=dict, help_text='Extracted preview info (e.g. channel names, amplitude min/max, summary text)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='studies.sleepstudy')),
            ],
            options={
                'db_table': 'studies_studyfile',
                'ordering': ('epoch_index', 'file_name'),
            },
        ),
        migrations.AddIndex(
            model_name='sleepstudy',
            index=models.Index(fields=['patient', '-study_date'], name='studies_sle_patient_38d451_idx'),
        ),
        migrations.AddIndex(
            model_name='sleepstudy',
            index=models.Index(fields=['status', '-created_at'], name='studies_sle_status_e1bf66_idx'),
        ),
        migrations.AddIndex(
            model_name='studyfile',
            index=models.Index(fields=['study', 'file_type'], name='studies_stu_study_i_75bfaf_idx'),
        ),
        migrations.AddIndex(
            model_name='studyfile',
            index=models.Index(fields=['study', 'epoch_index'], name='studies_stu_study_i_b70d64_idx'),
        ),
    ]
