# Generated by Django 5.2.17 on 2026-09-24 09:11

import common.utils.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=common.utils.uuid.get_uuid7, editable=False, primary_key=True, serialize=False)),
                ('opencode_session_id', models.CharField(blank=True, default='', help_text='Underlying session ID registered on the OpenCode server', max_length=128)),
                ('title', models.CharField(default='Study Clinical Consultation', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='studies.sleepstudy')),
            ],
            options={
                'db_table': 'assistant_chatsession',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=common.utils.uuid.get_uuid7, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('physician', 'Physician (Doctor)'), ('assistant', 'AI Assistant (OpenCode)'), ('system', 'System Context')], default='physician', max_length=20)),
                ('content', models.TextField()),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.chatsession')),
            ],
            options={
                'db_table': 'assistant_chatmessage',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['study', '-created_at'], name='assistant_c_study_i_c29a97_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['physician', '-created_at'], name='assistant_c_physici_746c51_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='assistant_c_session_1d652c_idx'),
        ),
    ]
