# Generated by Django 5.2.17 on 2026-09-24 09:11

import common.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=common.utils.uuid.get_uuid7, editable=False, primary_key=True, serialize=False)),
                ('mrn', models.CharField(db_index=True, help_text='Unique Medical Record Number for clinical tracking', max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('biological_sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other / Not Disclosed')], default='other', max_length=10)),
                ('medical_history', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients_patient',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx'), models.Index(fields=['-created_at'], name='patients_pa_created_15d2a5_idx')],
            },
        ),
    ]
