# Generated by Django 5.2.17 on 2026-09-24 09:11

import common.utils.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepEpoch',
            fields=[
                ('id', models.UUIDField(default=common.utils.uuid.get_uuid7, editable=False, primary_key=True, serialize=False)),
                ('epoch_index', models.PositiveIntegerField(help_text='0-indexed 30-second block order (0, 1, 2... N)')),
                ('start_seconds', models.FloatField(help_text='Offset from recording start in seconds')),
                ('stage', models.SmallIntegerField(choices=[(-1, 'Unscored / Artifact'), (0, 'Wake'), (1, 'N1 (Light Sleep)'), (2, 'N2 (Core Sleep)'), (3, 'N3 (Deep / Slow Wave Sleep)'), (4, 'REM (Dream Sleep)')], default=-1, help_text='Active clinical sleep stage')),
                ('ai_predicted_stage', models.SmallIntegerField(choices=[(-1, 'Unscored / Artifact'), (0, 'Wake'), (1, 'N1 (Light Sleep)'), (2, 'N2 (Core Sleep)'), (3, 'N3 (Deep / Slow Wave Sleep)'), (4, 'REM (Dream Sleep)')], default=-1, help_text='Original algorithmic prediction from staging model')),
                ('confidence', models.FloatField(default=1.0, help_text='AI staging confidence score [0.0 - 1.0]')),
                ('is_manually_corrected', models.BooleanField(db_index=True, default=False, help_text='True if modified by doctor')),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('correction_reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_lights_off', models.BooleanField(default=True, help_text='True if epoch falls inside lights-off window')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epoch_corrections', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, help_text='Optional link to raw epoch file if parsed from discrete reports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epochs', to='studies.studyfile')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epochs', to='studies.sleepstudy')),
            ],
            options={
                'db_table': 'hypnograms_sleepepoch',
                'ordering': ('study', 'epoch_index'),
                'indexes': [models.Index(fields=['study', 'epoch_index'], name='hypnograms__study_i_9ad797_idx'), models.Index(fields=['study', 'stage'], name='hypnograms__study_i_19c07d_idx'), models.Index(fields=['study', 'is_manually_corrected'], name='hypnograms__study_i_e94df9_idx')],
                'constraints': [models.UniqueConstraint(fields=('study', 'epoch_index'), name='unique_study_epoch_index')],
            },
        ),
    ]
