# Generated by Django 5.2.17 on 2026-09-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypnograms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepepoch',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Per-epoch micro-metrics (band powers, spindle detection, micro-arousals, EMG tone)'),
        ),
    ]
