# Generated by Django 5.2.17 on 2026-09-24 09:11

import common.utils.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalReport',
            fields=[
                ('id', models.UUIDField(default=common.utils.uuid.get_uuid7, editable=False, primary_key=True, serialize=False)),
                ('llm_model_name', models.CharField(default='opencode/default', help_text='Name of LLM model/version that generated the initial draft', max_length=128)),
                ('executive_summary', models.TextField(help_text="Narrative overview of patient's night and major impressions")),
                ('architecture_findings', models.TextField(blank=True, default='', help_text='Detailed evaluation of sleep stages, efficiency, and continuity')),
                ('respiratory_and_micro_notes', models.TextField(blank=True, default='', help_text='Evaluation of apneas, spindles, and arousals')),
                ('differential_diagnoses', models.JSONField(blank=True, default=list, help_text='Array of potential sleep disorders flagged for clinical attention')),
                ('clinical_recommendations', models.JSONField(blank=True, default=list, help_text='Array of actionable clinical recommendations (CPAP, CBT-I, etc.)')),
                ('physician_notes', models.TextField(blank=True, default='', help_text="Doctor's personal annotations, edits, or overrides")),
                ('is_signed_off', models.BooleanField(db_index=True, default=False, help_text='True if approved and signed off by the supervising physician')),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_report', to='studies.sleepstudy')),
            ],
            options={
                'db_table': 'reports_clinicalreport',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_signed_off', '-created_at'], name='reports_cli_is_sign_39229d_idx')],
            },
        ),
    ]
