# Generated by Django 5.2.17 on 2026-09-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalreport',
            name='raw_markdown',
            field=models.TextField(blank=True, default='', help_text='Full untouched clinical markdown report generated by LLM'),
        ),
    ]
