# Generated by Django 5.2.17 on 2026-09-24 09:11

import common.utils.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('key', models.CharField(help_text="Machine-readable key matching metrics_data (e.g. 'se_pct', 'waso_min')", max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('continuity', 'Continuity'), ('fragmentation', 'Fragmentation'), ('architecture', 'Architecture'), ('spectral', 'EEG Spectral & Band Power'), ('complexity', 'EEG Complexity'), ('microstructure', 'Microstructure'), ('respiratory', 'Muscle & Respiration'), ('custom', 'Experimental / Custom')], db_index=True, max_length=30)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('normal_min', models.FloatField(blank=True, help_text='Lower threshold of healthy clinical reference range', null=True)),
                ('normal_max', models.FloatField(blank=True, help_text='Upper threshold of healthy clinical reference range', null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_editable', models.BooleanField(default=True, help_text='Allows doctor manual adjustment if indicated')),
                ('is_active', models.BooleanField(default=True, help_text='Include in metrics computations')),
                ('show_in_report', models.BooleanField(default=True, help_text='Display on the final clinical narrative report')),
                ('display_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'db_table': 'metrics_metricdefinition',
                'ordering': ('category', 'display_order', 'key'),
            },
        ),
        migrations.CreateModel(
            name='MetricOverride',
            fields=[
                ('id', models.UUIDField(default=common.utils.uuid.get_uuid7, editable=False, primary_key=True, serialize=False)),
                ('metric_key', models.CharField(db_index=True, help_text="Key of adjusted metric (e.g. 'waso_min', 'se_pct')", max_length=64)),
                ('original_value', models.FloatField()),
                ('adjusted_value', models.FloatField()),
                ('clinical_rationale', models.TextField(help_text="Physician's documented reason for adjusting the metric")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_overrides', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_overrides', to='studies.sleepstudy')),
            ],
            options={
                'db_table': 'metrics_metricoverride',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['study', 'metric_key'], name='metrics_met_study_i_435c47_idx'), models.Index(fields=['physician', '-created_at'], name='metrics_met_physici_d7af52_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudyMetricsSummary',
            fields=[
                ('id', models.UUIDField(default=common.utils.uuid.get_uuid7, editable=False, primary_key=True, serialize=False)),
                ('sqi_score', models.FloatField(db_index=True, help_text='Composite Sleep Quality Index [0.0 - 100.0]')),
                ('sqi_category', models.CharField(choices=[('optimal', 'Optimal (> 85)'), ('good', 'Good (75 - 84)'), ('fair', 'Fair (60 - 74)'), ('poor', 'Poor (< 60)')], db_index=True, max_length=20)),
                ('metrics_data', models.JSONField(default=dict, help_text="Dynamic dictionary of computed metric values (e.g. {'waso_min': 45.0, 'se_pct': 82.5})")),
                ('ai_raw_metrics', models.JSONField(default=dict, help_text='Original unadjusted algorithm output')),
                ('category_summaries', models.JSONField(default=dict, help_text='Grouped scores: continuity, fragmentation, architecture, spectral, microstructure, respiratory')),
                ('overrides', models.JSONField(blank=True, default=dict, help_text='Active manual overrides: {metric_key: {original, override, reason, updated_at}}')),
                ('is_manually_adjusted', models.BooleanField(db_index=True, default=False, help_text='True if any metric was manually adjusted by the physician')),
                ('clinical_alerts', models.JSONField(blank=True, default=list)),
                ('is_valid', models.BooleanField(default=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_summary', to='studies.sleepstudy')),
            ],
            options={
                'db_table': 'metrics_studymetricssummary',
                'ordering': ('-computed_at',),
                'indexes': [models.Index(fields=['sqi_category', '-sqi_score'], name='metrics_stu_sqi_cat_952233_idx'), models.Index(fields=['is_manually_adjusted'], name='metrics_stu_is_manu_762c3c_idx')],
            },
        ),
    ]
